### PR TITLE
allow use relative path in setting

### PR DESCRIPTION
**Pull request by yinhui87**
after loaded setting,if php_bin use relative path,convert it to abs path

### CODE REVIEW

**Comment by ccirello** [comment]
Please, update the commit message to English.

**Comment by ccirello** [comment]
What's the intention of this change? I might be mistaken, but when no absolute path is provided it will resort to environment configuration to look for PHP binary. This change seem to defeat this expected behavior.

**Comment by yinhui87** [comment]
in win env, protable version is popular. uaually we integrate all needed binary in sublime to make the protable version can use everywhere without install php or add php to path. but phpfmt is not allow use relative path to config php binaty path, so I add some code to distinguish if the php_bin in setting is relative path, convert it to abs path

**Comment by yinhui87** [comment]
Its work in windows, I dont know will it work well also in linux or mac

**Comment by yinhui87** [comment]
in win env, protable version is popular. uaually we integrate all needed binary in sublime to make the protable version can use everywhere without install php or add php to path. but phpfmt is not allow use relative path to config php binaty path, so I add some code to distinguish if the php_bin in setting is relative path, convert it to abs path






At 2016-04-10 16:22:51, "C Cirello" <notifications@github.com> wrote:


What's the intention of this change? I might be mistaken, but when no absolute path is provided it will resort to environment configuration to look for PHP binary. This change seem to defeat this expected behavior.

**Comment by ccirello** [comment]
So I foresee some extra work. Please, ensure it works everywhere and not just your own specific use case. Also, write your commit messages in English. I am closing this PR for now. Reopen it is only after rework.

**Pull request closed without merging**
